# Generated by Django 5.1.1 on 2024-09-21 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'ordering': ['nome', 'data']},
        ),
        migrations.AddField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
