# Generated by Django 4.2.18 on 2025-01-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.medico'),
        ),
    ]
