# Generated by Django 4.2.18 on 2025-02-05 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_medico_especialidade_alter_procedimento_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='medico',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.medico', verbose_name='medico'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.paciente', verbose_name='paciente'),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
