# Generated by Django 4.2.18 on 2025-02-06 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='data_nasc',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='data_nasc',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='data_nasc',
            new_name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
